import type { InvokeArgs, MockCommandHandler } from './types';
import {
  contacts,
  rules,
  remoteImageTrusts,
  renderMessageWithPolicy,
  createMockContact,
  updateMockContact,
  deleteMockContact,
  mergeMockContacts,
  importMockContactsVCard,
  mockPickContactImportFile,
  mockPreviewContactImport,
  mockCommitContactImport,
  mockListContactImportBatches,
  mockUndoContactImportBatch,
  upsertMockRule,
  setMockRuleEnabled,
  deleteMockRule,
  trustMockRemoteImages,
  deleteMockRemoteImageTrust,
  renderMockMessageWithRemoteImagesOnce,
} from './state';

export const handlers: Record<string, MockCommandHandler> = {
  'list_contacts': () => contacts,
  'create_contact': createMockContact,
  'update_contact': updateMockContact,
  'delete_contact': deleteMockContact,
  'merge_contacts': mergeMockContacts,
  'import_contacts_vcard': importMockContactsVCard,
  'pick_contact_import_file': mockPickContactImportFile,
  'preview_contact_import': mockPreviewContactImport,
  'commit_contact_import': mockCommitContactImport,
  'list_contact_import_batches': mockListContactImportBatches,
  'undo_contact_import_batch': mockUndoContactImportBatch,
  'export_contacts_vcard': () => ({
    path: '/tmp/better-email-contacts.vcf',
    contacts: contacts.length,
    size_bytes: contacts.length * 180,
  }),
  'list_rules': () => rules,
  'upsert_rule': upsertMockRule,
  'set_rule_enabled': setMockRuleEnabled,
  'delete_rule': deleteMockRule,
  'list_remote_image_trusts': () => remoteImageTrusts,
  'trust_remote_images': trustMockRemoteImages,
  'delete_remote_image_trust': deleteMockRemoteImageTrust,
  'render_message_with_remote_image_policy': (args) => renderMessageWithPolicy(Number(args?.messageId)),
  'render_message_with_remote_images_once': renderMockMessageWithRemoteImagesOnce,
};
